version: "2.2"
services:
  ####################################### Gitlab Runner #######################################
  gitlab-runner:
    container_name: 'gitlab-runner'
    restart: unless-stopped
    build: 
      context: .
      dockerfile: docker/Dockerfile-gitlab-runner
      args:
        - GITLAB_RUNNER_VERSION:${GITLAB_RUNNER_VERSION}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - tls-cert
      - source: gitlab-runner-config
        target: /etc/gitlab-runner/config.toml
    cpus: 1
    mem_limit: 500M

networks: 
  gitlab-vault_gitlab-backend:
    external: true

secrets:
  gitlab-runner-config:
    file: ./conf/gitlab-runner/docker-gitlab-runner.toml
  tls-cert:
    file: ./conf/tls/tls.crt
