version: '3.9'
services:
  ######################################## Gitlab ########################################
  gitlab:
    image: gitlab/gitlab-ce:13.8.1-ce.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.hackinglab.local`)"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.docker.network=traefik_traefik-net"
      - "traefik.http.services.gitlab.loadbalancer.server.port=443"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        from_file('/omnibus_config.rb')
        external_url "https://gitlab.hackinglab.local:443/"
    configs:
      - source: gitlab-config
        target: /omnibus_config.rb
    secrets:
      - gitlab-root-password
      - gitlab-postgres-gitlab-password
    networks: 
      - traefik_traefik-net
      - gitlab-backend
    ports:
      - '2222:22'
    depends_on:
      - redis
      - postgres
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
    deploy:
      resources:
        limits:
          ##cpus: '2'
          memory: 3G
        reservations:
          ##cpus: '1'
          memory: 300M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s
  
  ######################################## Docker Registry ########################################
  registry:
    image: registry:2.7.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.hackinglab.local`)"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.docker.network=traefik_traefik-net"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
    environment: 
      - REGISTRY_HTTP_HOST=https://registry.hackinglab.local
    configs:
      - source: docker-registry-config
        target: /etc/docker/registry/config.yml
    networks: 
      - traefik_traefik-net
      - gitlab-backend
    volumes: 
      - registry-data:/var/lib/registry
    deploy:
      resources:
        limits:
          #cpus: '1'
          memory: 150M
        reservations:
          #cpus: '0.25'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

  ######################################## Redis ########################################
  redis:
    image: redis:6.0.10
    volumes:
      - redis-data:/var/lib/redis:Z
    networks: 
      - gitlab-backend
    deploy:
      resources:
        limits:
          #cpus: '1'
          memory: 150M
        reservations:
          #cpus: '0.25'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

  ######################################## Postgres ########################################
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=gitlabhq_production
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD_FILE=/run/secrets/gitlab-postgres-gitlab-password
    secrets:
      - gitlab-postgres-gitlab-password
    configs:
      - source: postgres-extension-script
        target: /docker-entrypoint-initdb.d/postgres-extension-script.sh
        mode: 0755
    networks: 
      - gitlab-backend
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          #cpus: '2'
          memory: 300M
        reservations:
          #cpus: '0.5'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 50
        window: 120s

volumes:
  gitlab-data:
  gitlab-config:
  gitlab-logs:
  redis-data:
  postgresql-data:
  registry-data:

secrets:
  tls-key:
    file: ./conf/tls/tls.key
  tls-cert:
    file: ./conf/tls/tls.crt
  gitlab-postgres-gitlab-password:
    external: true
  gitlab-root-password:
    external: true

networks:
  gitlab-backend:
  traefik_traefik-net:
    external: true

configs:
  postgres-extension-script:
    file: ./conf/postgres/entrypoint-extensions.sh
  gitlab-config:
    file: ./conf/gitlab/gitlab_small.rb
  nginx-config:
    file: ./conf/nginx/nginx.conf
  nginx-gitlab-config:
    file: ./conf/nginx/nginx_gitlab.conf
  nginx-docker-registry:
    file: ./conf/nginx/nginx_docker_registry.conf
  docker-registry-config:
    file: ./conf/registry/config.yml