ARG POSTGRES_VERSION
FROM postgres:${POSTGRES_VERSION}
COPY conf/postgres/entrypoint-extensions.sh /docker-entrypoint-initdb.d/postgres-extension-script.sh
RUN chmod +x /docker-entrypoint-initdb.d/postgres-extension-script.sh