ARG NGINX_VERSION
FROM nginx:${NGINX_VERSION}

# Copy TLS
COPY conf/tls/*.crt /etc/ssl/certs/nginx.crt
COPY conf/tls/*.key /etc/ssl/private/nginx.key

# Copy NGINX configs
# LEAVE the EXTRA `.conf` because it is chopped when evaluated
COPY conf/nginx/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx/nginx_gitlab.conf /etc/nginx/templates/gitlab.conf.conf
COPY conf/nginx/nginx_docker_registry.conf /etc/nginx/templates/docker-registry.conf.conf