concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Ubuntu-VM"
  url = "{{ gitlab_runner_url }}"
  token = "{{ gitlab_runner_token }}"
  tls-ca-file = "/etc/gitlab-runner/certs/gitlab.crt"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]